server:
  port: 8084 # Gateway will run on port 8084

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: Order-Service
          uri: lb://ORDER-SERVICE  # lb:// means load-balancing through Eureka
          predicates:
            - Path=/order/**
          filters:
            - AuthenticationFilter 
        - id: User-Service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter 
        - id: Mobile-Service
          uri: lb://MOBILE-SERVICE
          predicates:
            - Path=/mobile/**
          filters:
            - AuthenticationFilter 
        - id: Authentication-Server
          uri: lb://AUTHENTICATION-SERVER
          predicates:
            - Path=/auth-server/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"



